package-lock.json, package.json, test-server/index.js
- developer can now run` npm run tserver ` to run a dev environment with a server for testing...
=> Implemented local SSE server for testing

src/client/components/ReqResCtrl.js, src/client/components/containers/ReqResContainer.jsx, src/client/components/display/ReqRes.jsx, src/client/components/display/Request.jsx, src/client/components/display/Response.jsx, src/client/reducers/business.js
- Updated - Res/Req Component Response Stream
- Formatting Updates
- Dev merge fixes
=> Updated - Res/Req Component Response Stream

src/client/components/ReqResCtrl.js, src/client/components/display/ModalNewRequest.jsx, src/server/server.js
updated parsing for SSE
merge with Kyle's pretty print
=> Nov 17, 1114am

src/client/actions/actionTypes.js, src/client/actions/actions.js, src/client/components/display/ModalNewRequest.jsx, src/client/components/display/ModalWarning.jsx, src/client/components/display/ReqRes.jsx, src/client/reducers/business.js, src/client/reducers/ui.js
Validation checking for request modal and implement remove button for ReqRes
=> Nov 17 4pm

src/client/components/ReqResCtrl.js
- Button functionality 100%
- Code Reactor
=> Button functionality 100%

src/client/components/Modal/NewRequest/ModalNewRequest.jsx, src/client/components/containers/NavContainer.jsx
=> Nov 21 7:00 PM

src/client/components/containers/ResponseContainer.jsx, src/client/components/display/ReqRes.jsx, src/client/controllers/httpController.js
=> 11.26 12:11PM

main.js, package-lock.json, src/client/components/containers/App.jsx, src/client/components/display/Graph.jsx, src/client/controllers/httpController.js, test-server/server.js
=> 11.28 12:30am

main.js, package-lock.json, package.json, src/assets/style/sidebar.scss, src/client/components/Modal/NewRequest/BodyEntryForm.jsx, src/client/components/Modal/NewRequest/BodyTypeSelect.jsx, src/client/components/Modal/NewRequest/HeaderEntryForm.jsx, src/client/components/Modal/NewRequest/JSONTextArea.jsx, src/client/components/Modal/NewRequest/ModalNewRequest.jsx, src/client/components/Modal/NewRequest/ProtocolSelect.jsx, src/client/components/display/ReqRes.jsx, src/client/components/display/Request.jsx
=> 11.28 4:45pm

src/assets/style/App.scss, src/assets/style/cookieTable.scss, src/client/components/display/CookieTable.jsx, src/client/components/display/CookieTableCell.jsx, src/client/components/display/CookieTableRow.jsx, src/client/components/display/ResponseTabs.jsx, src/client/components/display/Tab.jsx, src/client/controllers/httpController.js
we are going to have to set a min width on the response containers as the tables are too scrunched up if there are more than 2 on my big screen, but i built a table from scratch and it seems to work pretty well.
=>  COOKIE MONSTER!!! - cookies displaying in tab

src/assets/style/sidebar.scss, src/client/components/display/History.jsx
sidebar scroll + styling fix
sidebar does not add to modal now on delete
=> 12.2.18 1:25PM

src/assets/style/chart.scss, src/assets/style/sidebar.scss, src/client/components/Modal/NewRequest/JSONTextArea.jsx, src/client/components/display/Graph.jsx
=> 12.2 3:47PM

src/assets/style/chart.scss, src/assets/style/colors.scss, src/assets/style/sidebar.scss, src/client/components/Modal/NewRequest/BodyEntryForm.jsx, src/client/components/Modal/NewRequest/BodyTypeSelect.jsx, src/client/components/Modal/NewRequest/FieldEntryForm.jsx, src/client/components/Modal/NewRequest/Header.jsx, src/client/components/Modal/NewRequest/HeaderEntryForm.jsx, src/client/components/Modal/NewRequest/JSONTextArea.jsx, src/client/components/Modal/NewRequest/ModalNewRequest.jsx, src/client/components/Modal/NewRequest/WWWField.jsx, src/client/components/Modal/NewRequest/WWWForm.jsx
=> 12.2 8:43pm

src/assets/style/sidebar.scss, src/client/components/Modal/NewRequest/BodyEntryForm.jsx, src/client/components/Modal/NewRequest/CookieEntryForm.jsx, src/client/components/Modal/NewRequest/ModalNewRequest.jsx, src/client/components/Modal/Warning/ModalWarning.jsx, src/client/components/containers/HistoryContainer.jsx, src/client/components/display/History.jsx, src/client/controllers/httpController.js, src/client/reducers/business.js
=> 12.3.18 1:16pm

src/client/components/containers/SingleReqResContainer.jsx
- RoundTrip removed for WebSockets and GraphQL Subscription method
- Negative RoundTrip Bug fixed
=> Fixed RoundTrip Bug

src/assets/style/grid.scss, src/client/controllers/httpController.js
-Enables sse functionality for public urls that use SSE- (Our deployed heroku server functions)
-caveat is that http is slower as a result of checking if sse before fetching(Need to fix)
=> Fix heroku sse

httpserver.js, package-lock.json, package.json, src/client/components/display/ResponseHeadersDisplay.jsx, src/client/controllers/graphQLController.js, src/client/controllers/httpController.js
=> Cookie Authentication

src/assets/style/navbar.scss, src/assets/style/sidebar.scss, src/client/components/composer/NewRequest/ComposerNewRequest.jsx, src/client/components/containers/NavBarContainer.jsx
Co-authored-by: Paul Rhee <youjun27@gmail.com>
=> minor ui updates for buttons and background

ISSUE_TEMPLATE.md, package.json
includes the following updates:
- package.json file includes team 3.0 as contributors
- issue template
- contributing template
=> merging latest updates to dev

.github/workflows/unit-tests.yml
WebRTC has officially been moved from “experimental features” to “core features”!
Text channel improvements:
Added “Add Answer” button and functionality to be able to complete a channel connection
Completed functionality for two-way communication via text channel
Debugged messaging in response window - now the remote user’s incoming messages are visible
Video channel improvements:
Enabled audio on video calls
Added an audio toggle button for turning audio on and off
Audio-only channel completed
Finished implementing an audio channel begun by a previous group
Updated dependencies and versions to un-deprecate the app and make it usable (see “How to download and test the application locally?”)
Added a React Joyride tour to introduce users to the app and ease their introduction to it
Added a …
=> feat: WebRTC integration and front-end updates (take 2)

.github/workflows/createPackages.yml
WebRTC has officially been moved from “experimental features” to “core features”!
Text channel improvements:
Added “Add Answer” button and functionality to be able to complete a channel connection
Completed functionality for two-way communication via text channel
Debugged messaging in response window - now the remote user’s incoming messages are visible
Video channel improvements:
Enabled audio on video calls
Added an audio toggle button for turning audio on and off
Audio-only channel completed
Finished implementing an audio channel begun by a previous group
Updated dependencies and versions to un-deprecate the app and make it usable (see “How to download and test the application locally?”)
Added a React Joyride tour to introduce users to the app and ease their introduction to it
Added a …
=> feat: WebRTC integration and front-end updates (with linux release action updates)
